language: node_js
node_js:
  - "6"
  - "7"
os:
  - linux
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
install:
  - npm install
  - npm install -g codecov
script:
  - npm run lint
  - npm run test
after_success:
  - cat ./coverage/lcov.info | codecov
  - npm run semantic-release
